name: Ozan Keysan 
owner:
  name: Ozan Keysan
  position: Assistant Professor
  department: Electrical-Electronics Engineering
  departmentweb: http://eee2.metu.edu.tr
  company: METU
  companyweb: http://www.metu.edu.tr
  avatar: ozan.jpg

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     #"with_toc_data"]

#markdown: kramdown
#pygments: true
